---
Core:
  listen: 2000
  interface: 0.0.0.0
  logLevel: info
  queues:
    - id: ripQ
      name: disc ripping
    - id: encodeQ
      name: video encoding
  redis:
    host: localhost
    port: 6379
    password: ''
Ripper:
  enable: 'auto'
  device: /dev/sr0
  # owner: 1000
  # group: 0
  # disc: 0
  output: /rips
  dvdbackupOpts:
    '-M': ''
    '-p': ''
    '-v': ''
  makemkvOpts:
    - backup
    - '--decrypt'
    - '--progress=-stdout'
    - '--robot'
  # mkvKey: abcdefg
Encoder:
  enable: 'auto'
  output: /media
  input: /rips
  # owner: 1000
  # group: 0
  hbOpts:
    '--preset': High Profile
    '--optimize': ''
    '--quality': 21
    '--cfr': ''
    '--main-feature': ''
    # - '--min-duration=3600'
  avOpts:
    '-strict experimental': ''
    '-c': 'copy'
